version: '3.8'
services:
  angularfrontend:
    container_name: angularfrontend
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    ports: 
     - 4200:4200
    command: ng serve --host=0.0.0.0
    restart: always
  
  nodesanitizingservice:
    container_name: nodesanitizingservice
    build:
      context: .
      dockerfile: Dockerfile_SanitizingService
    networks:
    - db_network
    ports:
    - 8080:8080
    command: node index.js
    restart: always

  nodebackend:
    container_name: nodebackend
    build:
      context: .
      dockerfile: Dockerfile_Backend
    networks:
    - db_network
    ports:
    - 8081:8081
    command: node -r dotenv/config index.js
    depends_on:
      - mongodb
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    

  mongodb:
    image: mongo:latest
    networks:
      - db_network
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    restart: always

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
    - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  db_network:
    driver: bridge
