version: '3.8'
services:
  angularfrontend:
    container_name: angularfrontend
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    ports: 
     - 4200:4200
    command: ng serve --host=0.0.0.0
  
  nodemiddleware:
    container_name: nodemiddleware
    build:
      context: .
      dockerfile: Dockerfile_Middleware
    # networks:
    # - db_network
    ports:
    - 8080:8080
    command: node index.js

  nodebackend:
    container_name: nodebackend
    build:
      context: .
      dockerfile: Dockerfile_Backend
    networks:
    - db_network
    ports:
    - 8081:8081
    command: node index.js
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    networks:
      - db_network
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=websecurity
      - MONGO_INITDB_ROOT_PASSWORD=secure_password!

networks:
  db_network:
    driver: bridge
